# Generated by Django 5.2.9 on 2025-12-30 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_pics'),
        ),
    ]
