# Generated by Django 5.2.9 on 2025-12-30 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_created_at_travel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='image',
        ),
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_pics')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.travel')),
            ],
        ),
    ]
