# Generated by Django 5.2.9 on 2025-12-30 07:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_travel_image_travelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='TravelImage',
        ),
    ]
