# Generated by Django 5.2.9 on 2025-12-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_likes_post_likes'),
        ('travel', '0004_alter_travel_description_delete_travelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='travels', to='blog.tag'),
        ),
    ]
