# Generated by Django 5.2.9 on 2025-12-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymous_likes',
            field=models.IntegerField(default=0),
        ),
    ]
